# This is a basic workflow to help you get started with Actions
name: CI
on: 
  push:
     branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: run one line scripts
      run: pwd;ls -ltr ; chmod 775 c1t.sh ; ./c1t.sh
      



